Numpy Functions

In [2]:
import numpy as np

np.sort / return a sotred copy of an array

In [11]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)
print(a)

[68 29 75 97 90 70 27 13 87 12 50  9 48 93 88]


In [10]:
print(b)

[[ 5 63 21 88]
 [39 97 25 95]
 [56 77  6 15]
 [59 91 10 37]
 [51 29 94 81]
 [ 9 63  6 72]]


In [15]:
print(np.sort(a))
print(np.sort(b)) # it will sort row wise automatically
# if you want your sort on colom wise
print(np.sort(b,axis=0))

[ 9 12 13 27 29 48 50 68 70 75 87 88 90 93 97]
[[20 38 44 57]
 [ 3  7 93 98]
 [ 6 13 15 15]
 [12 26 29 96]
 [ 2 22 28 30]
 [33 35 87 91]]
[[12 15  7  2]
 [13 29 15  3]
 [22 30 20  6]
 [33 57 26 44]
 [38 91 28 87]
 [93 98 35 96]]


In [17]:
# if you your sorting on decending order
print(np.sort(a)[::-1])

[97 93 90 88 87 75 70 68 50 48 29 27 13 12  9]


np.append() / The numpy.append() appends vlaues along the mentioned axis at the end of the array.

In [22]:
np.append(a,200)

array([ 68,  29,  75,  97,  90,  70,  27,  13,  87,  12,  50,   9,  48,
        93,  88, 200])

In [30]:
np.append(b,np.zeros((b.shape[0],1)),axis=1)

array([[38., 57., 20., 44.,  0.],
       [93., 98.,  7.,  3.,  0.],
       [13., 15., 15.,  6.,  0.],
       [12., 29., 26., 96.,  0.],
       [22., 30., 28.,  2.,  0.],
       [33., 91., 35., 87.,  0.]])

np.concetenate() / Concetenate a sequence of arrays along an existing axis.

In [32]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [34]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique() / we can get the unique values from an array given as parameter in np.unique() method.

In [36]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [38]:
np.unique(e)
np.unique(f)

array([1, 2, 3])

np.expand_dims() / we can get the expanded dimension of an array

In [39]:
np.expand_dims(a,axis=1)

array([[68],
       [29],
       [75],
       [97],
       [90],
       [70],
       [27],
       [13],
       [87],
       [12],
       [50],
       [ 9],
       [48],
       [93],
       [88]], dtype=int32)

np.where() / returns the indices of elements in an input array where the given condition is satisfied.

In [40]:
a

array([68, 29, 75, 97, 90, 70, 27, 13, 87, 12, 50,  9, 48, 93, 88],
      dtype=int32)

In [41]:
# find all the indices with value greater than 50.
np.where(a>50)

(array([ 0,  2,  3,  4,  5,  8, 13, 14]),)

In [42]:
# Replace all values which greater than 50 with 0. 
# np.where(condition, True,Flase) Syntax. 
np.where(a>50,0,a)


array([ 0, 29,  0,  0,  0,  0, 27, 13,  0, 12, 50,  9, 48,  0,  0],
      dtype=int32)

In [43]:
np.where(a%2==0,'Even',a)

array(['Even', '29', '75', '97', 'Even', 'Even', '27', '13', '87', 'Even',
       'Even', '9', 'Even', '93', 'Even'], dtype='<U11')

np.argmax() / return indices of the max element of the array in a particular axis.

In [45]:
np.argmax(a)

np.int64(3)

In [49]:
np.argmax(b,axis=1)

array([1, 1, 1, 3, 1, 1])

In [48]:
b

array([[38, 57, 20, 44],
       [93, 98,  7,  3],
       [13, 15, 15,  6],
       [12, 29, 26, 96],
       [22, 30, 28,  2],
       [33, 91, 35, 87]], dtype=int32)

In [50]:
np.argmin(b,axis=1)

array([2, 3, 3, 0, 3, 0])

np.cumsum() / when we want to compute the cumulative sum of array elements over a given axis. 

In [51]:
np.cumsum(a)

array([ 68,  97, 172, 269, 359, 429, 456, 469, 556, 568, 618, 627, 675,
       768, 856])

In [53]:
np.cumsum(b,axis=1)

array([[ 38,  95, 115, 159],
       [ 93, 191, 198, 201],
       [ 13,  28,  43,  49],
       [ 12,  41,  67, 163],
       [ 22,  52,  80,  82],
       [ 33, 124, 159, 246]])

np.percentile() / compute the nth percentile of the given data(array elements) along the specified axis.

In [55]:
np.percentile(a,100)

np.float64(97.0)

In [56]:
np.percentile(a,50)

np.float64(68.0)

In [57]:
np.median(a)

np.float64(68.0)

np.histogram() / it tells us the frequency count on a given data. (array element).

In [59]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 2, 0, 1, 1, 1, 2, 2, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

np.corrcoef() / returns Pearson product-moment correlation coeffients.

In [60]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [61]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

isin() / we can that one array having values are checked in a differet numpy array having different elements with different sizes.

In [64]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([90, 70, 50], dtype=int32)

np.put() / replaces specific elements of an array with given values of p_array. Array indexes works on flattened array. 

In [69]:
np.put(a,[0,1],[110,530])
a

array([110, 530,  75,  97,  90,  70,  27,  13,  87,  12,  50,   9,  48,
        93,  88], dtype=int32)

np.delete() / returns a new array with the deletion of sub array along with the mentioned axis.

In [71]:
np.delete(a,0)

array([530,  75,  97,  90,  70,  27,  13,  87,  12,  50,   9,  48,  93,
        88], dtype=int32)